// Code generated by "enumer -type EventType -trimprefix EventType -json -text -transform=snake"; DO NOT EDIT.

//
package game

import (
	"encoding/json"
	"fmt"
)

const _EventTypeName = "unknownwindrawnotification"

var _EventTypeIndex = [...]uint8{0, 7, 10, 14, 26}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventTypeIndex)-1) {
		return fmt.Sprintf("EventType(%d)", i)
	}
	return _EventTypeName[_EventTypeIndex[i]:_EventTypeIndex[i+1]]
}

var _EventTypeValues = []EventType{0, 1, 2, 3}

var _EventTypeNameToValueMap = map[string]EventType{
	_EventTypeName[0:7]:   0,
	_EventTypeName[7:10]:  1,
	_EventTypeName[10:14]: 2,
	_EventTypeName[14:26]: 3,
}

// EventTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func EventTypeString(s string) (EventType, error) {
	if val, ok := _EventTypeNameToValueMap[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to EventType values", s)
}

// EventTypeValues returns all values of the enum
func EventTypeValues() []EventType {
	return _EventTypeValues
}

// IsAEventType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i EventType) IsAEventType() bool {
	for _, v := range _EventTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for EventType
func (i EventType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for EventType
func (i *EventType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("EventType should be a string, got %s", data)
	}

	var err error
	*i, err = EventTypeString(s)
	return err
}

// MarshalText implements the encoding.TextMarshaler interface for EventType
func (i EventType) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for EventType
func (i *EventType) UnmarshalText(text []byte) error {
	var err error
	*i, err = EventTypeString(string(text))
	return err
}
